-- 3. Inserção de Dados Massiva (50 Produtos, 100 Vendas, 15 Erros)
-- Gerado via script para garantir inserts explícitos (Sem Loop SQL).
SET NOCOUNT ON;

-- Limpeza
TRUNCATE TABLE Vendas;
DELETE FROM Estoque;
TRUNCATE TABLE Auditoria_Divergencias;

-- 1. Popular Estoque (50 Produtos)
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (1, 'Smartphone Razer 796', 130);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (2, 'Console Apple 225', 179);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (3, 'Smartwatch Logitech 759', 149);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (4, 'Monitor Sony 900', 142);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (5, 'Teclado HP 966', 182);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (6, 'Notebook Acer 191', 82);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (7, 'Notebook Logitech 705', 48);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (8, 'Notebook Apple 647', 14);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (9, 'Smartphone Dell 939', 82);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (10, 'Smartphone Sony 446', 117);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (11, 'Notebook Samsung 239', 102);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (12, 'Cadeira Acer 899', 192);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (13, 'Tablet Acer 326', 37);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (14, 'Monitor Sony 367', 20);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (15, 'Console Razer 801', 56);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (16, 'Headset Logitech 429', 151);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (17, 'Teclado Logitech 568', 64);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (18, 'Mouse Sony 932', 162);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (19, 'Cadeira Razer 203', 197);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (20, 'Teclado HP 762', 40);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (21, 'Notebook Apple 967', 54);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (22, 'Smartphone Sony 116', 137);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (23, 'Cadeira Asus 425', 106);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (24, 'Console Dell 987', 24);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (25, 'Smartwatch Logitech 986', 73);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (26, 'Tablet Razer 293', 15);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (27, 'Tablet Sony 992', 112);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (28, 'Tablet Samsung 337', 10);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (29, 'Console Razer 768', 39);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (30, 'Smartphone Sony 455', 153);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (31, 'Monitor Razer 802', 198);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (32, 'Monitor Razer 992', 125);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (33, 'Smartphone HP 815', 136);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (34, 'Notebook Acer 386', 55);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (35, 'Smartphone Samsung 111', 106);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (36, 'Headset Dell 125', 143);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (37, 'Teclado Logitech 258', 163);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (38, 'Tablet LG 219', 187);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (39, 'Notebook Samsung 516', 48);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (40, 'Tablet Logitech 924', 33);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (41, 'Console Dell 706', 35);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (42, 'Mouse LG 521', 186);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (43, 'Smartphone Apple 861', 187);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (44, 'Notebook Dell 425', 18);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (45, 'Tablet Razer 926', 150);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (46, 'Console Sony 418', 163);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (47, 'Cadeira Logitech 782', 101);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (48, 'Tablet Apple 965', 186);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (49, 'Console Acer 942', 140);
INSERT INTO Estoque (ProdutoID, Nome, QuantidadeAtual) VALUES (50, 'Cadeira Dell 576', 53);

-- 2. Inserção de Vendas
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (12, 4, DATEADD(HOUR, -79, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (36, 3, DATEADD(HOUR, -60, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (26, 4, DATEADD(HOUR, -10, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (12, 1, DATEADD(HOUR, -92, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (44, 3, DATEADD(HOUR, -93, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (5, 2, DATEADD(HOUR, -97, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (13, 3, DATEADD(HOUR, -17, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (999, 1, DATEADD(HOUR, -3, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (15, 3, DATEADD(HOUR, -87, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (999, 5, DATEADD(HOUR, -17, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (11, 3, DATEADD(HOUR, -36, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (16, 2, DATEADD(HOUR, -60, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (27, 2, DATEADD(HOUR, -23, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (18, 4, DATEADD(HOUR, -45, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (999, 5, DATEADD(HOUR, -24, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (26, 4, DATEADD(HOUR, -77, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (35, 4, DATEADD(HOUR, -42, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (40, 4, DATEADD(HOUR, -6, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (39, 2, DATEADD(HOUR, -2, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (15, 1, DATEADD(HOUR, -15, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (24, 4, DATEADD(HOUR, -81, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (31, 2, DATEADD(HOUR, -8, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (48, 3, DATEADD(HOUR, -17, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (38, 4, DATEADD(HOUR, -9, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (999, 2, DATEADD(HOUR, -87, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (18, 2, DATEADD(HOUR, -89, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (28, 1, DATEADD(HOUR, -90, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (5, 3, DATEADD(HOUR, -56, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (46, 4, DATEADD(HOUR, -58, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (45, 1, DATEADD(HOUR, -32, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (30, 1, DATEADD(HOUR, -56, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (29, 1, DATEADD(HOUR, -70, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (8, 1, DATEADD(HOUR, -88, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (34, 3, DATEADD(HOUR, -89, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (14, 3, DATEADD(HOUR, -46, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (8, 4, DATEADD(HOUR, -86, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (29, 2, DATEADD(HOUR, -99, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (10, 2, DATEADD(HOUR, -94, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (24, 3, DATEADD(HOUR, -60, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (26, 2, DATEADD(HOUR, -35, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (33, 4, DATEADD(HOUR, -83, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (14, 4, DATEADD(HOUR, -94, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (40, 3, DATEADD(HOUR, -98, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (5, 3, DATEADD(HOUR, -90, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (1, 4, DATEADD(HOUR, -40, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (32, 2, DATEADD(HOUR, -44, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (46, 4, DATEADD(HOUR, -88, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (20, 1, DATEADD(HOUR, -18, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (999, 1, DATEADD(HOUR, -80, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (999, 1, DATEADD(HOUR, -70, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (19, 3, DATEADD(HOUR, -11, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (17, 4, DATEADD(HOUR, -43, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (33, 4, DATEADD(HOUR, -11, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (999, 5, DATEADD(HOUR, -72, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (43, 2, DATEADD(HOUR, -33, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (16, 3, DATEADD(HOUR, -21, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (25, 2, DATEADD(HOUR, -6, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (999, 2, DATEADD(HOUR, -12, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (12, 2, DATEADD(HOUR, -70, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (27, 2, DATEADD(HOUR, -58, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (38, 2, DATEADD(HOUR, -82, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (24, 2, DATEADD(HOUR, -33, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (17, 1, DATEADD(HOUR, -94, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (40, 2, DATEADD(HOUR, -70, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (21, 2, DATEADD(HOUR, -45, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (45, 3, DATEADD(HOUR, -45, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (999, 5, DATEADD(HOUR, -55, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (31, 2, DATEADD(HOUR, -44, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (999, 2, DATEADD(HOUR, -42, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (26, 3, DATEADD(HOUR, -14, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (16, 3, DATEADD(HOUR, -41, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (37, 2, DATEADD(HOUR, -12, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (36, 4, DATEADD(HOUR, -21, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (22, 4, DATEADD(HOUR, -15, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (17, 2, DATEADD(HOUR, -96, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (27, 4, DATEADD(HOUR, -68, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (16, 4, DATEADD(HOUR, -22, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (9, 4, DATEADD(HOUR, -73, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (9, 4, DATEADD(HOUR, -8, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (13, 4, DATEADD(HOUR, -33, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (8, 3, DATEADD(HOUR, -79, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (6, 1, DATEADD(HOUR, -96, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (34, 4, DATEADD(HOUR, -21, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (40, 1, DATEADD(HOUR, -37, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (999, 4, DATEADD(HOUR, -18, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (15, 2, DATEADD(HOUR, -81, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (10, 4, DATEADD(HOUR, -78, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (999, 4, DATEADD(HOUR, -67, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (6, 4, DATEADD(HOUR, -73, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (21, 1, DATEADD(HOUR, -97, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (999, 4, DATEADD(HOUR, -16, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (2, 4, DATEADD(HOUR, -92, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (40, 1, DATEADD(HOUR, -52, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (3, 4, DATEADD(HOUR, -83, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (36, 2, DATEADD(HOUR, -2, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (32, 3, DATEADD(HOUR, -23, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (12, 1, DATEADD(HOUR, -5, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (999, 3, DATEADD(HOUR, -85, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (999, 5, DATEADD(HOUR, -84, GETDATE()));
INSERT INTO Vendas (ProdutoID, QuantidadeVendida, DataVenda) VALUES (23, 3, DATEADD(HOUR, -72, GETDATE()));
-- Resumo Final
SELECT 
    (SELECT COUNT(*) FROM Vendas) AS TotalVendasGeradas,
    (SELECT COUNT(*) FROM Vendas WHERE ProdutoID = 999) AS VendasComErroPropositais,
    (SELECT COUNT(*) FROM Estoque) AS TotalProdutos;

SELECT 'Carga de dados concluída via INSERTS manuais.' AS Info;
